"""
Post-training int8 quantization + C export for the AVR MLP path (`kws_model.h`).

Loads a float `MLP208_KWS` checkpoint (see `train.py --arch mlp`), calibrates scales on
`data/aug`, writes int8 weights, int32 biases, float scales, and MFCC mean/std to match
`firmware/src/main.c` / `mfcc.c`.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, Tuple

import numpy as np
import torch
from torch.utils.data import DataLoader

from dataset_kws import (
    CLASS_NAMES,
    AugWavDataset,
    compute_global_mfcc_mean_std,
    load_training_checkpoint,
)
from model import MLP208_KWS

LOG2_Q_MFCC = 12
MFCC_I8_SHR = 20  # must match mfcc.h MFCC_NORM_SHR


def compute_mfcc_int_params(mean: np.ndarray, std: np.ndarray, s_x: float) -> Tuple[np.ndarray, np.ndarray]:
    mean64 = mean.astype(np.float64)
    std64 = np.maximum(std.astype(np.float64), 1e-6)
    mean_q12 = np.round(mean64 * (1 << LOG2_Q_MFCC)).astype(np.int32)
    d = (float(1 << LOG2_Q_MFCC)) * std64 * float(s_x)
    mul = np.round((1 << MFCC_I8_SHR) / d).astype(np.float64)
    mul = np.clip(mul, -2147483648.0, 2147483647.0).astype(np.int32)
    return mean_q12, mul


def compute_fc1_int_rescale(s_x: float, s_w1: float, s_h: float) -> Tuple[int, int]:
    r = (float(s_x) * float(s_w1)) / float(s_h)
    acc_max = 4_000_000
    out_mul = 1
    out_shr = 20
    for shr in range(15, 29):
        mul = int(round(r * (1 << shr)))
        if mul == 0:
            continue
        if abs(acc_max * mul) < (1 << 62):
            out_mul, out_shr = mul, shr
            break
    return out_mul, out_shr


def manual_ptq_mlp(
    model: MLP208_KWS,
    calib_x: torch.Tensor,
) -> Dict[str, object]:
    """
    Min–max symmetric int8 matching `kws_run_inference` in `main.c`:
      fc1: acc_f = (b1_i32 + dot(w1_q, x_q)) * (S_x * S_w1), ReLU, hidden_q = round(acc_f / S_h)
      fc2: out_i32 = b2_i32 + dot(w2_q, hidden_q)  with W2_f * S_h ≈ K * W2_q
    """
    model.eval()
    with torch.no_grad():
        w1 = model.fc1.weight.detach()
        b1 = model.fc1.bias.detach()
        w2 = model.fc2.weight.detach()
        b2 = model.fc2.bias.detach()

    eps = 1e-8
    s_x = float(calib_x.abs().max().item() / 127.0) + eps
    x_q = torch.clamp(torch.round(calib_x / s_x), -128, 127).to(torch.int32)

    s_w1 = float(w1.abs().max().item() / 127.0) + eps
    w1_q = torch.clamp(torch.round(w1 / s_w1), -128, 127).to(torch.int32)

    b1_i32 = torch.round(b1 / (s_x * s_w1)).to(torch.int32)

    z1 = (x_q @ w1_q.T) + b1_i32.unsqueeze(0)
    pre = z1.to(torch.float32) * (s_x * s_w1)
    h_f = torch.relu(pre)
    s_h = float(h_f.abs().max().item() / 127.0) + eps
    h_q = torch.clamp(torch.round(h_f / s_h), -128, 127).to(torch.int32)

    a = (w2 * s_h).detach()
    k = float(a.abs().max().item() / 127.0) + eps
    w2_q = torch.clamp(torch.round(a / k), -128, 127).to(torch.int32)
    b2_i32 = torch.round(b2 / k).to(torch.int32)

    logits_q = (h_q.to(torch.float32) @ w2_q.T.to(torch.float32)) + b2_i32.to(torch.float32)

    logits_f = model(calib_x)
    pred_f = logits_f.argmax(dim=1)
    pred_q = logits_q.argmax(dim=1)
    acc_q = float((pred_f == pred_q).float().mean().item())

    return {
        "s_x": s_x,
        "s_w1": s_w1,
        "s_h": s_h,
        "k_fc2": k,
        "w1_q": w1_q.cpu().numpy().astype(np.int8),
        "b1_i32": b1_i32.cpu().numpy().astype(np.int32),
        "w2_q": w2_q.cpu().numpy().astype(np.int8),
        "b2_i32": b2_i32.cpu().numpy().astype(np.int32),
        "calib_argmax_match": acc_q,
    }


def _c_array_int8_2d(name: str, arr: np.ndarray) -> str:
    assert arr.dtype == np.int8
    rows = []
    for i in range(arr.shape[0]):
        cols = ", ".join(str(int(x)) for x in arr[i].tolist())
        rows.append(f"  {{ {cols} }}")
    body = ",\n".join(rows)
    return f"const int8_t {name}[{arr.shape[0]}][{arr.shape[1]}] PROGMEM = {{\n{body}\n}};"


def _c_array_int32_1d(name: str, arr: np.ndarray) -> str:
    assert arr.dtype == np.int32
    vals = ", ".join(str(int(x)) for x in arr.tolist())
    return f"const int32_t {name}[{arr.shape[0]}] PROGMEM = {{ {vals} }};"


def _c_array_float32_1d(name: str, arr: np.ndarray) -> str:
    assert arr.dtype == np.float32
    vals = ", ".join(f"{float(x):.8f}f" for x in arr.tolist())
    return f"const float {name}[{arr.shape[0]}] PROGMEM __attribute__((aligned(4))) = {{ {vals} }};"


def emit_c_sources(
    out_c: Path,
    mean: np.ndarray,
    std: np.ndarray,
    ptq: Dict[str, object],
) -> None:
    out_c.parent.mkdir(parents=True, exist_ok=True)
    w1 = ptq["w1_q"]
    b1 = ptq["b1_i32"]
    w2 = ptq["w2_q"]
    b2 = ptq["b2_i32"]
    mean_q12, mfcc_mul = compute_mfcc_int_params(mean, std, float(ptq["s_x"]))
    lines = [
        "/* Auto-generated by training/export.py — do not edit by hand. */",
        "#include <avr/pgmspace.h>",
        "#include <stdint.h>",
        "",
        '#include "kws_model.h"',
        "",
        _c_array_int8_2d("kws_fc1_w", w1),
        "",
        _c_array_int32_1d("kws_fc1_b", b1),
        "",
        _c_array_int8_2d("kws_fc2_w", w2),
        "",
        _c_array_int32_1d("kws_fc2_b", b2),
        "",
        _c_array_float32_1d("kws_input_mean", mean.astype(np.float32)),
        "",
        _c_array_float32_1d("kws_input_std", std.astype(np.float32)),
        "",
        _c_array_int32_1d("kws_mfcc_mean_q12", mean_q12),
        "",
        _c_array_int32_1d("kws_mfcc_i8_mul", mfcc_mul),
        "",
    ]
    out_c.write_text("\n".join(lines) + "\n", encoding="utf-8")


def emit_scales_header(out_h: Path, ptq: Dict[str, object]) -> None:
    out_h.parent.mkdir(parents=True, exist_ok=True)
    fc1_mul, fc1_shr = compute_fc1_int_rescale(
        float(ptq["s_x"]), float(ptq["s_w1"]), float(ptq["s_h"])
    )
    text = "\n".join(
        [
            "/* Auto-generated by training/export.py — do not edit by hand. */",
            "/*",
            f"  float scales: s_x={ptq['s_x']:.10e}  s_w1={ptq['s_w1']:.10e}  s_h={ptq['s_h']:.10e}",
            f"  fc2 K={ptq['k_fc2']:.10e}",
            "*/",
            "#ifndef KWS_MODEL_SCALES_GENERATED_H",
            "#define KWS_MODEL_SCALES_GENERATED_H",
            "",
            f"#define KWS_FC1_RESCALE_MUL ({fc1_mul}L)",
            f"#define KWS_FC1_RESCALE_SHR {fc1_shr}",
            "",
            "#endif",
            "",
        ]
    )
    out_h.write_text(text, encoding="utf-8")


def main() -> None:
    p = argparse.ArgumentParser(description="PTQ (int8) export for MLP208_KWS -> AVR C.")
    p.add_argument(
        "--checkpoint",
        type=Path,
        required=True,
        help="Float checkpoint from train.py --arch mlp (dict with state_dict + MFCC stats).",
    )
    p.add_argument(
        "--data-root",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "data" / "aug",
        help="Augmented WAVs for PTQ calibration.",
    )
    p.add_argument("--sr", type=int, default=8000)
    p.add_argument("--batch-size", type=int, default=64)
    p.add_argument(
        "--calib-max-samples",
        type=int,
        default=4096,
        help="Cap calibration set size (for speed).",
    )
    p.add_argument(
        "--out-c",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "firmware" / "src" / "kws_model.c",
    )
    p.add_argument(
        "--out-scales-h",
        type=Path,
        default=Path(__file__).resolve().parent.parent
        / "firmware"
        / "include"
        / "kws_model_scales.generated.h",
    )
    p.add_argument(
        "--placeholder-header",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "firmware" / "include" / "model_data.h",
        help="Optional: refresh placeholder model_data.h (not used by AVR MLP path).",
    )
    args = p.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    arch, state, mean_ckpt, std_ckpt = load_training_checkpoint(args.checkpoint, device)
    if arch != "mlp":
        raise SystemExit(
            f"Checkpoint arch is {arch!r}; int8 export requires --arch mlp training checkpoint."
        )

    if mean_ckpt is None or std_ckpt is None:
        mean, std = compute_global_mfcc_mean_std(args.data_root, args.sr, CLASS_NAMES)
    else:
        mean, std = mean_ckpt, std_ckpt

    ds = AugWavDataset(args.data_root, sr=args.sr, mfcc_mean=mean, mfcc_std=std)
    loader = DataLoader(ds, batch_size=args.batch_size, shuffle=False, num_workers=0)

    xs = []
    n = 0
    for xb, _ in loader:
        xs.append(xb)
        n += xb.size(0)
        if n >= args.calib_max_samples:
            break
    if not xs:
        raise SystemExit("No calibration batches.")
    calib_x = torch.cat(xs, dim=0)[: args.calib_max_samples].to(device)

    model = MLP208_KWS(num_classes=len(CLASS_NAMES)).to(device)
    model.load_state_dict(state)

    ptq = manual_ptq_mlp(model, calib_x)
    print(
        f"PTQ calibration: {calib_x.size(0)} frames  |  argmax match vs float: "
        f"{100.0 * float(ptq['calib_argmax_match']):.2f}%"
    )
    print(f"  scales: s_x={ptq['s_x']:.6g}  s_w1={ptq['s_w1']:.6g}  s_h={ptq['s_h']:.6g}  k_fc2={ptq['k_fc2']:.6g}")

    emit_c_sources(args.out_c, mean, std, ptq)
    emit_scales_header(args.out_scales_h, ptq)
    print("Wrote", args.out_c.resolve())
    print("Wrote", args.out_scales_h.resolve())

    ph = args.placeholder_header
    ph.parent.mkdir(parents=True, exist_ok=True)
    ph.write_text(
        "/* Placeholder — AVR build uses kws_model.c + kws_model_scales.generated.h */\n"
        "#ifndef MODEL_DATA_H\n#define MODEL_DATA_H\n#include <stdint.h>\n#endif\n",
        encoding="utf-8",
    )
    print("Wrote", ph.resolve())


if __name__ == "__main__":
    main()
